In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, 1:4].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[['Malaysia' 44.0 72000.0]
 ['Singapore' 27.0 48000.0]
 ['Thailand' 30.0 nan]
 ['Indonesia' nan 61000.0]
 ['Indonesia' 40.0 25000.0]
 ['Singapore' 35.0 58000.0]
 ['Thailand' 40.0 52000.0]
 ['Malaysia' 48.0 nan]
 ['Indonesia' 50.0 83000.0]
 ['China' 30.0 67000.0]]


In [5]:
print(y)

['No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [7]:
print(x)

[['Malaysia' 44.0 72000.0]
 ['Singapore' 27.0 48000.0]
 ['Thailand' 30.0 58250.0]
 ['Indonesia' 38.22222222222222 61000.0]
 ['Indonesia' 40.0 25000.0]
 ['Singapore' 35.0 58000.0]
 ['Thailand' 40.0 52000.0]
 ['Malaysia' 48.0 58250.0]
 ['Indonesia' 50.0 83000.0]
 ['China' 30.0 67000.0]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [22]:
print(x)

[[0.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 0.0 27.0 48000.0]
 [0.0 0.0 0.0 0.0 1.0 30.0 58250.0]
 [0.0 1.0 0.0 0.0 0.0 38.22222222222222 61000.0]
 [0.0 1.0 0.0 0.0 0.0 40.0 25000.0]
 [0.0 0.0 0.0 1.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 0.0 1.0 40.0 52000.0]
 [0.0 0.0 1.0 0.0 0.0 48.0 58250.0]
 [0.0 1.0 0.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 0.0 30.0 67000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[0 1 0 1 0 1 1 1 0 1]


In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [14]:
print(x_train)

[[0.0 0.0 0.0 0.0 1.0 40.0 52000.0]
 [0.0 1.0 0.0 0.0 0.0 40.0 25000.0]
 [0.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 0.0 38.22222222222222 61000.0]
 [0.0 0.0 0.0 1.0 0.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 0.0 48.0 58250.0]
 [0.0 1.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 1.0 0.0 35.0 58000.0]]


In [15]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 30.0 58250.0]
 [1.0 0.0 0.0 0.0 0.0 30.0 67000.0]]


In [16]:
print(y_train)

[1 0 0 1 1 1 0 1]


In [17]:
print(y_test)

[0 1]


In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [30]:
print(x_train)

[[0.0 0.0 0.0 -0.5773502691896258 2.645751311064591 -0.04048881650894582
  -0.3221581110696072]
 [0.0 1.0 0.0 -0.5773502691896258 -0.37796447300922725
  -0.04048881650894582 -2.009095129034096]
 [0.0 0.0 1.0 -0.5773502691896258 -0.37796447300922725 0.5425501412198737
  0.9274248652003845]
 [0.0 1.0 0.0 -0.5773502691896258 -0.37796447300922725
  -0.2996172421661991 0.24015422825188906]
 [0.0 0.0 0.0 1.7320508075688774 -0.37796447300922725 -1.9353654291276092
  -0.5720747063236056]
 [0.0 0.0 1.0 -0.5773502691896258 -0.37796447300922725 1.1255890989486934
  0.06833656901476523]
 [0.0 1.0 0.0 -0.5773502691896258 -0.37796447300922725 1.4171085778131032
  1.6146955021488798]
 [0.0 0.0 0.0 1.7320508075688774 -0.37796447300922725 -0.7692875136699702
  0.05271678181139032]]


In [31]:
print(x_test)

[[0.0 0.0 0.0 -0.5773502691896258 2.645751311064591 -1.4980862108309945
  0.06833656901476523]
 [1.0 0.0 0.0 -0.5773502691896258 -0.37796447300922725
  -1.4980862108309945 0.6150291211328867]]
